const yts = require('yt-search');

/**
 * GET /api/youtube/search?q=QUERY
 * Searches YouTube Music — prioritises "official audio" (Topic channel)
 * versions which are embeddable, unlike official music videos.
 */
const searchYouTube = async (req, res) => {
  try {
    const { q } = req.query;

    if (!q || q.trim() === '') {
      return res.status(400).json({ message: 'Search query is required.' });
    }

    const base = q.trim();

    // Search "official audio" first to get YouTube Music Topic-channel versions
    // These are auto-generated by YouTube Music and are always embeddable
    const [officialResult, fallbackResult] = await Promise.all([
      yts(`${base} official audio`),
      yts(`${base} audio`),
    ]);

    // Prefer Topic-channel videos (channelName ends with " - Topic")
    // then "official audio" videos, then anything else
    const score = (video) => {
      const ch = (video.author?.name || '').toLowerCase();
      const title = (video.title || '').toLowerCase();
      if (ch.endsWith('- topic') || ch.endsWith(' topic')) return 3;
      if (title.includes('official audio')) return 2;
      if (title.includes('audio')) return 1;
      return 0;
    };

    // Merge both result sets, dedupe by videoId, sort by score
    const allVideos = [
      ...officialResult.videos,
      ...fallbackResult.videos,
    ];
    const seen = new Set();
    const deduped = allVideos.filter((v) => {
      if (seen.has(v.videoId)) return false;
      seen.add(v.videoId);
      return true;
    });

    const sorted = deduped
      .sort((a, b) => score(b) - score(a))
      .slice(0, 10);

    const results = sorted.map((video) => ({
      videoId: video.videoId,
      title: video.title,
      channelName: video.author?.name || 'Unknown Artist',
      thumbnail:
        video.thumbnail ||
        `https://i.ytimg.com/vi/${video.videoId}/mqdefault.jpg`,
      duration: video.timestamp,
      views: video.views,
      // Flag Topic-channel videos so UI can show a "Music" badge
      isMusicChannel:
        (video.author?.name || '').toLowerCase().includes('topic'),
    }));

    res.status(200).json({ results });
  } catch (error) {
    console.error('YouTube Music search error:', error.message);

    if (error.message?.includes('timeout') || error.code === 'ECONNABORTED') {
      return res.status(504).json({
        message: 'Search timed out. Please try again.',
        results: [],
      });
    }

    res.status(500).json({
      message: 'Failed to search. Please try again.',
      results: [],
    });
  }
};

/**
 * GET /api/youtube/trending
 * Returns trending/popular music — fetched live from YouTube
 */
const TRENDING_QUERIES = [
  'trending music 2025',
  'top hits 2025',
  'popular songs 2025',
];

const getTrending = async (req, res) => {
  try {
    const query = TRENDING_QUERIES[Math.floor(Math.random() * TRENDING_QUERIES.length)];
    const result = await yts(query);

    const seen = new Set();
    const videos = result.videos
      .filter((v) => {
        if (seen.has(v.videoId)) return false;
        seen.add(v.videoId);
        return true;
      })
      .slice(0, 16)
      .map((video) => ({
        videoId: video.videoId,
        title: video.title,
        channelName: video.author?.name || 'Unknown Artist',
        thumbnail:
          video.thumbnail ||
          `https://i.ytimg.com/vi/${video.videoId}/mqdefault.jpg`,
        duration: video.timestamp,
        views: video.views,
        isMusicChannel: (video.author?.name || '').toLowerCase().includes('topic'),
      }));

    res.status(200).json({ videos });
  } catch (error) {
    console.error('Trending fetch error:', error.message);
    res.status(500).json({ message: 'Failed to fetch trending.', videos: [] });
  }
};

/**
 * GET /api/youtube/suggestions?videoId=ID
 * Returns song suggestions based on the currently playing song
 */
const getSuggestions = async (req, res) => {
  try {
    const { videoId, title } = req.query;

    if (!videoId && !title) {
      return res.status(400).json({ message: 'videoId or title required.', videos: [] });
    }

    // Use the song title to find related music
    const searchQuery = title
      ? `${title} similar songs audio`
      : `music like ${videoId}`;

    const result = await yts(searchQuery);

    const seen = new Set();
    if (videoId) seen.add(videoId); // Don't include the current song

    const videos = result.videos
      .filter((v) => {
        if (seen.has(v.videoId)) return false;
        seen.add(v.videoId);
        return true;
      })
      .slice(0, 12)
      .map((video) => ({
        videoId: video.videoId,
        title: video.title,
        channelName: video.author?.name || 'Unknown Artist',
        thumbnail:
          video.thumbnail ||
          `https://i.ytimg.com/vi/${video.videoId}/mqdefault.jpg`,
        duration: video.timestamp,
        views: video.views,
        isMusicChannel: (video.author?.name || '').toLowerCase().includes('topic'),
      }));

    res.status(200).json({ videos });
  } catch (error) {
    console.error('Suggestions fetch error:', error.message);
    res.status(500).json({ message: 'Failed to fetch suggestions.', videos: [] });
  }
};

module.exports = { searchYouTube, getTrending, getSuggestions };
